# Generated by Django 5.2.3 on 2025-07-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='anio_fabricacion',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='matricula',
        ),
        migrations.AddField(
            model_name='avion',
            name='columnas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avion',
            name='filas',
            field=models.IntegerField(default=0),
        ),
    ]
