# Generated by Django 5.2.3 on 2025-07-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
